[package]
name = "nuntium"
version = "0.1.0"
edition = "2021"

[dependencies]
tun = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
byteorder = "1.5"
pnet = "0.35.0"
pqcrypto-kyber = "0.8.1"
pqcrypto-traits = "0.3.5"
