networks:
  nuntium-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

services:
  node-a:
    security_opt:
      - seccomp:unconfined
    privileged: true
    build: .
    image: nuntium:ubuntu
    container_name: node-a
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    networks:
      nuntium-net:
        ipv4_address: 172.30.0.3
    command: ["/usr/local/bin/wait-for-it.sh", "server:5072", "--", "nuntium", "client"]
    init: true


  node-b:
    security_opt:
      - seccomp:unconfined
    privileged: true
    build: .
    image: nuntium:ubuntu
    container_name: node-b
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    networks:
      nuntium-net:
        ipv4_address: 172.30.0.4
    command: ["/usr/local/bin/wait-for-it.sh", "server:5072", "--", "nuntium", "client"]
    init: true

  server:
    security_opt:
      - seccomp:unconfined
    privileged: true
    build: .
    image: nuntium:ubuntu
    container_name: server
    cap_add:
      - NET_ADMIN
    networks:
      nuntium-net:
        ipv4_address: 172.30.0.2
    command: ["nuntium", "server"]
    init: true
