version: "3.8"

networks:
  nuntium-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

services:
  node-a:
    build: .
    image: nuntium:ubuntu
    container_name: node-a
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    security_opt:
      - seccomp:unconfined
    sysctls:
      net.core.rmem_max: 134217728
      net.core.wmem_max: 134217728
      net.ipv4.tcp_rmem: "4096 87380 134217728"
      net.ipv4.tcp_wmem: "4096 65536 134217728"
      net.ipv4.tcp_congestion_control: bbr
    networks:
      nuntium-net:
        ipv4_address: 172.30.0.3
    command: ["/usr/local/bin/wait-for-it.sh", "server:5072", "--", "nuntium", "client"]
    init: true

  node-b:
    build: .
    image: nuntium:ubuntu
    container_name: node-b
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    security_opt:
      - seccomp:unconfined
    sysctls:
      net.core.rmem_max: 134217728
      net.core.wmem_max: 134217728
      net.ipv4.tcp_rmem: "4096 87380 134217728"
      net.ipv4.tcp_wmem: "4096 65536 134217728"
      net.ipv4.tcp_congestion_control: bbr
    networks:
      nuntium-net:
        ipv4_address: 172.30.0.4
    command: ["/usr/local/bin/wait-for-it.sh", "server:5072", "--", "nuntium", "client"]
    init: true

  server:
    build: .
    image: nuntium:ubuntu
    container_name: server
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    security_opt:
      - seccomp:unconfined
    sysctls:
      net.core.rmem_max: 134217728
      net.core.wmem_max: 134217728
      net.ipv4.tcp_rmem: "4096 87380 134217728"
      net.ipv4.tcp_wmem: "4096 65536 134217728"
      net.ipv4.tcp_congestion_control: bbr
    networks:
      nuntium-net:
        ipv4_address: 172.30.0.2
    command: ["nuntium", "server"]
    init: true

  monitor:
    image: nicolaka/netshoot
    container_name: monitor
    network_mode: "container:server"
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - ./captures:/captures
    entrypoint: ["tcpdump", "-i", "eth0", "-nn", "-w", "/captures/server-capture.pcap"]
